Repository thehyve/fairspace, pull requests merged in 2024-01, with the labels that each got.

#1457 FAIRSPC-11:
  projects/mercury/src/metadata/common/values/DateValue.js
  projects/mercury/src/metadata/views/facets/DateSelectionFacet.js
Labels: bugfix

#1464 FAIRSPC-29: fixed numeric filter with forced casting to numeric (Post…
  projects/mercury/src/metadata/views/MetadataView.js
  projects/mercury/src/metadata/views/MetadataViewAPI.js
  projects/mercury/src/metadata/views/metadataViewUtils.js
  projects/saturn/src/main/java/io/fairspace/saturn/services/views/ViewFilter.java
  projects/saturn/src/main/java/io/fairspace/saturn/services/views/ViewStoreReader.java
Labels: bugfix

#1465 reduced number of db calls for viewstorereader
  projects/saturn/src/main/java/io/fairspace/saturn/services/views/ViewRow.java
  projects/saturn/src/main/java/io/fairspace/saturn/services/views/ViewRowCollection.java
  projects/saturn/src/main/java/io/fairspace/saturn/services/views/ViewStoreReader.java
Labels: don't merge yet

#1469 Fixed NPE for numeric filter
  projects/saturn/src/main/java/io/fairspace/saturn/services/views/ViewStoreReader.java
Labels: bugfix

#1455 Infra/fairspc 23 GitHub actions ci
  .github/workflows/build_and_upload_on_push_to_dev.yaml
  .github/workflows/build_on_pull_request.yaml
  .travis.yml
  .travis/add_pod_annotations.sh
  .travis/build-condition.sh
  .travis/build.sh
  .travis/ci-service-account.json.enc
Labels: improvement

#1470 Add support for external metadata views.
  README.adoc
  charts/fairspace/templates/project/configmap-pluto.yaml
  charts/fairspace/values.yaml
  projects/mercury/src/layout/MainMenu.js
  projects/mercury/src/layout/WorkspaceLayout.js
  projects/mercury/src/metadata/LinkedDataMetadataProvider.js
  projects/mercury/src/metadata/common/LinkedDataAPI.js
  projects/mercury/src/metadata/common/MetadataAPI.js
  projects/mercury/src/metadata/common/MetadataAPIPathContext.js
  projects/mercury/src/metadata/common/VocabularyAPI.js
  projects/mercury/src/metadata/external-sources/ExternalMetadataSourceContext.js
  projects/mercury/src/metadata/external-sources/ExternalMetadataSourceView.js
  projects/mercury/src/metadata/external-sources/__tests__/ExternalMetadataSourceView.js
  projects/mercury/src/metadata/external-sources/__tests__/externalMetadataSourceUtils.js
  projects/mercury/src/metadata/external-sources/externalMetadataSourceUtils.js
  projects/mercury/src/metadata/views/MetadataView.js
  projects/mercury/src/metadata/views/MetadataViewAPI.js
  projects/mercury/src/metadata/views/MetadataViewContext.js
  projects/mercury/src/metadata/views/UseViewData.js
  projects/mercury/src/metadata/views/metadataViewUtils.js
  projects/mercury/src/metadata/vocabulary/LinkedDataVocabularyProvider.js
  projects/mercury/src/metadata/vocabulary/VocabularyContext.js
  projects/mercury/src/routes/WorkspaceRoutes.js
  projects/pluto/src/main/java/nl/fairspace/pluto/config/Urls.java
  projects/pluto/src/main/java/nl/fairspace/pluto/config/dto/PlutoConfig.java
  projects/pluto/src/main/java/nl/fairspace/pluto/web/MetadataSourcesResource.java
  projects/pluto/src/main/java/nl/fairspace/pluto/web/dto/MetadataSourceInfo.java
  projects/pluto/src/main/resources/application-local.yml
Labels: enhancement

#1477 FAIRPC-29: reduced number of calls to db on metadata request per view
  projects/saturn/src/main/java/io/fairspace/saturn/App.java
  projects/saturn/src/main/java/io/fairspace/saturn/config/Services.java
  projects/saturn/src/main/java/io/fairspace/saturn/services/maintenance/MaintenanceService.java
  projects/saturn/src/main/java/io/fairspace/saturn/services/views/JdbcQueryService.java
  projects/saturn/src/main/java/io/fairspace/saturn/services/views/MaterializedViewService.java
  projects/saturn/src/main/java/io/fairspace/saturn/services/views/Table.java
  projects/saturn/src/main/java/io/fairspace/saturn/services/views/ViewRow.java
  projects/saturn/src/main/java/io/fairspace/saturn/services/views/ViewStoreClientFactory.java
  projects/saturn/src/main/java/io/fairspace/saturn/services/views/ViewStoreReader.java
  projects/saturn/src/main/java/io/fairspace/saturn/services/views/ViewUpdater.java
  projects/saturn/src/test/java/io/fairspace/saturn/services/health/HealthServiceTest.java
  projects/saturn/src/test/java/io/fairspace/saturn/services/views/JdbcQueryServiceTest.java
  projects/saturn/src/test/java/io/fairspace/saturn/services/views/ViewServiceTest.java
Labels: enhancement

#1478 FAIRPC-29: fixed failing metadata request when no records found
  projects/saturn/src/main/java/io/fairspace/saturn/services/views/ViewStoreReader.java
Labels: bugfix
